### ISSUE TITLE
LWE decryption formulas in code and paper differ

### ISSUE THREAD

**Issue by tkchia** [lducas/FHEW#1]
Good day,

It seems to me that the decryption formula in the implementation (LWE::Decrypt) disagrees with the decryption formula given in Section 3 of the paper. Can you kindly check?

I believe that the formula
"⌊t(b - a . s)q⌉ mod t"
on pages 5 and 6 of the paper should be
"⌊t(b - a . s) / q⌉ mod t".

Thank you!

**Comment by lducas** [comment]
Thank you tkchia, you are right !
I have corrected this mistake in the final version for Eurocrypt proceeding
but have postponed updating the eprint for too long...
I will do this shortly, thanks again for the reminder.

May I ask you what are your project with either the source code or the
article ?

Best regards

-- Leo Ducas

2015-02-20 17:16 GMT+01:00 tkchia <notifications@github.com>:

**Comment by tkchia** [comment]
Good day,

Thank you very much! At the moment I do not have any concrete projects which use FHE, if that is what you mean, though I am interested in information privacy and code obfuscation in general.

Thank you!

**Comment by lducas** [comment]
Thanks tkchia. Eprint has been updated.

**Comment by tkchia** [comment]
Thank you!
