### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by ShijiMariam** [lducas/FHEW#10]
I have fftw 3.3.5 and gcc version is 6.2.0 on ubuntu 16.10 64 bit machine. I am getting the following error while trying to run the makefile.
$make

g++ -Wall -O3 -c FFT.cpp
In file included from FFT.h:4:0,
                 from FFT.cpp:3:
params.h:26:31: warning: result of ‘(536870913 << 11)’ requires 42 bits to represent, but ‘int’ only has 32 bits [-Wshift-overflow=]
 const ZmodQ vgprime[3] = {v, v<<11, v<<22};
                              ~^~~~
params.h:26:38: warning: result of ‘(536870913 << 22)’ requires 53 bits to represent, but ‘int’ only has 32 bits [-Wshift-overflow=]
 const ZmodQ vgprime[3] = {v, v<<11, v<<22};
                                     ~^~~~
FFT.cpp: In function ‘void FFTforward(double (*)[2], const ZmodQ*)’:
FFT.cpp:24:15: error: expected primary-expression before ‘double’
     res[k] = (double complex) out[2*k+1];
               ^~~~~~
FFT.cpp:24:15: error: expected ‘)’ before ‘double’
FFT.cpp: In function ‘void FFTbackward(ZmodQ*, const double (*)[2])’:
FFT.cpp:29:19: error: expected primary-expression before ‘double’
     out[2*k+1] = (double complex) val[k]/N;
                   ^~~~~~
FFT.cpp:29:19: error: expected ‘)’ before ‘double’
FFT.cpp:30:19: error: expected primary-expression before ‘double’
     out[2*k]   = (double complex) 0;
                   ^~~~~~
FFT.cpp:30:19: error: expected ‘)’ before ‘double’
Makefile:30: recipe for target 'FFT.o' failed
make: *** [FFT.o] Error 1

**Comment by NanXiao** [comment]
I think PR #9 can fix this error.

**Comment by ShijiMariam** [comment]
Yes it worked. Thank you for your response.
