### ISSUE TITLE
Some questions about function MemberTest in FHEW library

### ISSUE THREAD

**Issue by xiaolei206** [lducas/FHEW#21]
Hello,
I have a perplexity about the MemberTest() function：
 for (int i = 0; i < N2; ++i)
      temp[i] = conj(((double complex) C[0][i]) * ((double complex)t[i]));  // Compute t*a
    FFTbackward(temp_ModQ, temp);
    for (int i = 0; i < N; ++i) ct->a[i] = temp_ModQ[i];
Can you tell me why conj is required here?

**Comment by lducas** [comment]
This may correspond to the transpositions in Algorithm 2 of the paper. Indeed, transposition is to be understood in its `hermitian' sense because we are working over a complex-multiplication ring.
