### ISSUE TITLE
win64-Compile errors

### ISSUE THREAD

**Issue by DKnight1900** [lducas/FHEW#6]
hi,I try to use yout FHEW in my win64 OS,but when i built following your tutorial i failed,and the errors just like this.would you please help me and thank you in advanced.
# 

g++ -Wall -O3 -c FFT.cpp
In file included from FFT.h:4:0,
                 from FFT.cpp:4:
params.h:25:1: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
params.h:18:36: warning: left shift count >= width of type [enabled by default]
FFT.cpp: In function 'void FFTforward(double (_)[2], const ZmodQ_)':
FFT.cpp:25:15: error: expected primary-expression before 'double'
FFT.cpp:25:15: error: expected ')' before 'double'
FFT.cpp: In function 'void FFTbackward(ZmodQ_, const double (_)[2])':
FFT.cpp:30:19: error: expected primary-expression before 'double'
FFT.cpp:30:19: error: expected ')' before 'double'
FFT.cpp:31:19: error: expected primary-expression before 'double'
FFT.cpp:31:19: error: expected ')' before 'double'
make: **\* [FFT.o] Error 1

**Comment by lducas** [comment]
I am sorry, I don't really know what is causing this, I've nvered us gcc under win64...

**Comment by matlink** [comment]
Have the same issue under g++ with `-std=c++11` as flag.

**Comment by lducas** [comment]
Solve by  PR #9
