### ISSUE TITLE
When is the bootstrapping done?

### ISSUE THREAD

**Issue by matlink** [lducas/FHEW#8]
I can't figure out where happens the bootstrapping. I don't see any `Refresh` or `Recrypt` function. I suppose then that the bootstrapping is always done at the end of the `HomNAND` function via `KeySwitch` and `ModSwitch` instructions?

**Comment by lducas** [comment]
Indeed, everything is inside HomNAND. The reason is that, unlike other other FHE schemes, homomorphic operations and refreshing are a bit mixed in FHEW.

**Comment by matlink** [comment]
Okay thank you, then I guess I have no way to test the execution time of
the refreshing operation?

Le 27/06/2016 à 10:47, Léo Ducas a écrit :

> Indeed, everything is inside HomNAND. The reason is that, unlike other
> other FHE schemes, homomorphic operations and refreshing are a bit
> mixed in FHEW.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/lducas/FHEW/issues/8#issuecomment-228687589, or
> mute the thread
> https://github.com/notifications/unsubscribe/AEPnHmJQwzhRH_YwIAH8hFOh9b5Q23zUks5qP44xgaJpZM4I-3vm.

## 

Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2

**Comment by lducas** [comment]
The price of Refresh is essentially the price of HomeNAND.
- L

2016-06-27 10:49 GMT+02:00 Matlink notifications@github.com:
